"""The supervised-learning table: one row per (realisation, job), with a guard.

7,140 rows -- 175 jobs and 63 rule-generated companions, each executed over 30
realisations -- joined to everything the planner legitimately knows about a job
before it runs. The label is the observed working time.

WHAT THIS FILE IS ACTUALLY FOR IS THE LEAKAGE GUARD.

The label is generated by
    actual = trunc_lognormal(duration_mean_min, duration_sd_min,
                             duration_min_min, duration_max_min)
(dsgen/demand.py:237). Those four columns are the label's own parameters. A
model given any of them is not predicting anything; it is reading the answer.
`uncertainty_level` is banded straight off sd/mean (demand.py:165), so it leaks
the same information one step removed.

Two more columns leak and are NOT obvious, which is the whole reason the guard
is an assertion over the assembled frame rather than a list in a docstring.
From dsgen/demand.py:212-213:

    "minimum_duration_min":   max(60, int(j.duration_mean_min))
    req = ceil((j.duration_mean_min + 1.0 * j.duration_sd_min) / 30) * 30
    "requested_duration_min": max(j.min_block_min, req)

`minimum_duration_min` IS duration_mean_min, integer-truncated and floored at
60. `requested_duration_min` carries the mean and the sd together. Both live in
block_requests.csv, both look like innocuous operational fields, and a join
that pulled the request table in wholesale would have leaked without anything
looking wrong.

WHAT REMAINS LEARNABLE, stated plainly because it bounds every result built on
this table. From demand.py:152-154, a job's parameters are

    mean = trunc_lognormal(catalogue_mean, catalogue_sd * 0.5, ...)
    sd   = catalogue_sd * uncertainty_scale * uniform(0.8, 1.25)

drawn per job from the ACTIVITY CATALOGUE and nothing else. Section geometry,
km span, protection flags, resource class, criticality and due day never enter
the duration path. So conditional on `activity`, the label is independent of
every other feature in this table, and E[actual | features] = E[actual |
activity]. The per-activity mean is therefore close to the best any model can
do on the legal feature set -- not a baseline to beat but a ceiling to
approach. That is a property of how this dataset was generated, not of the
model.

    python -m blockplan_ml.training_table --out <path.csv>
"""
from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from typing import Any

import pandas as pd

from blockplan_service import paths

LABEL = "actual_duration_min"

#: Columns that are the label's own generating parameters, or a deterministic
#: function of them. Matched by NAME against every joined source, so a column
#: cannot slip in because it arrived from a different table.
FORBIDDEN = frozenset({
    # the four parameters of the generating distribution
    "duration_mean_min",
    "duration_sd_min",
    "duration_min_min",
    "duration_max_min",
    # banded from sd/mean
    "uncertainty_level",
    # block_requests: computed from mean, and from mean+sd. See the module
    # docstring -- these are the two that do not announce themselves.
    "minimum_duration_min",
    "requested_duration_min",
})

#: Identity and bookkeeping. Not features, not the label; carried so the table
#: can be split by job or by realisation and audited afterwards.
KEYS = ("realisation", "job_id", "parent_job_id", "is_companion")

#: Columns that identify the row rather than describe it. Never features.
#:
#: The first two are join keys that arrived with a prefix and would otherwise
#: have been treated as data: request_job_id IS job_id, and request_request_id
#: is "R" plus the job number. Three more are echoes of the columns joined on.
#: location_desc is free text naming the exact kilometre ("JTJ-TPT UP km
#: 12.34") and identifies a job outright.
#:
#: Letting these through is how a model scores well on a random split and
#: collapses on an unseen job -- which is what happened here before they were
#: removed. See the evaluation report.
IDENTIFIERS = frozenset({
    "request_request_id",
    "request_job_id",
    "location_desc",
    "activity_activity_id",
    "section_section_id",
    "resource_resource_class",
})

#: Not identifiers, but nearly: each takes a distinct value for roughly 70% of
#: jobs, so a tree can use them to memorise individual jobs rather than learn
#: anything transferable.
#:
#: KEPT, and the measurement says to keep them. Dropping all four moves
#: job-holdout R2 from 0.484 to 0.487 -- three thousandths, against a fold
#: standard deviation of 0.2. They are not what was hurting the model.
#:
#: What WAS hurting it was the IDENTIFIERS above: removing those took
#: job-holdout from 0.294 to 0.484. The suspicion about near-identifiers was
#: reasonable and turned out to be wrong, so `profile=GENERALISING` remains
#: only to keep that check reproducible rather than a remembered claim.
NEAR_IDENTIFIERS = frozenset({
    "km_from", "km_to", "km_span", "criticality",
})

ALL_FEATURES = "all"
GENERALISING = "generalising"

#: The profile used when the planner actually consumes predictions.
#:
#: block_requests.csv exists only for the 175 jobs of the default demand set.
#: The other seven scenarios generate their own jobs and have no request rows,
#: so request_* features cannot be produced at plan time. Training on columns
#: that will be absent at serving is train/serve skew, and it is the kind that
#: does not announce itself -- the model simply degrades on the scenarios
#: nobody checked.
#:
#: Nothing is lost: every request_* column is derived from the job it belongs
#: to (dsgen/demand.py:188-220), so they carry no information the job does not
#: already carry.
SERVING = "serving"

#: Exactly the attributes a core.Job carries, plus what can be joined from the
#: reference tables using them.
#:
#: This is the serving contract. At plan time there is no jobs.csv row -- there
#: is a core.Job, built by load_scenario_jobs and expand_mandatory_pairings --
#: so anything not on that object cannot be a feature no matter how useful it
#: looks in the training frame. min_block_min, priority and provenance are all
#: in jobs.csv and none of them is a field of core.Job (core.py:92-123), so all
#: three are excluded here rather than discovered missing at inference.
SERVING_JOB_COLUMNS = (
    "dept", "activity", "section_id",
    "km_from", "km_to", "km_span",
    "needs_T", "needs_P", "needs_D",
    "needs_train_movements", "needs_live_ohe",
    "due_day", "criticality", "is_companion", "resource_class",
)


class LeakageError(AssertionError):
    """A forbidden column reached the feature set."""


def _p(*parts: str) -> str:
    return os.path.join(*parts)


def _read(name: str) -> pd.DataFrame:
    return pd.read_csv(_p(paths.PROCESSED_DIR, name))


# -- companions -------------------------------------------------------------

def companion_catalogue(pairing_rules: pd.DataFrame) -> dict[str, list[dict[str, Any]]]:
    """activity -> the rules it compels, in file order.

    core.expand_mandatory_pairings names each companion f"{parent}c{k}" where k
    indexes this list (core.py:239-240), and core.load_pairing_rules appends in
    CSV order (core.py:208). So position is the join key, and it has to match
    the file exactly.
    """
    table: dict[str, list[dict[str, Any]]] = {}
    for row in pairing_rules.to_dict("records"):
        table.setdefault(row["activity"], []).append(row)
    return table


def companion_rows(companions: pd.DataFrame, jobs: pd.DataFrame,
                   pairing_rules: pd.DataFrame) -> pd.DataFrame:
    """Give each companion the job attributes core.py gives it.

    Companion job_ids are not in jobs.csv -- they do not exist until
    expand_mandatory_pairings runs -- so their attributes are reconstructed the
    way core.py constructs them (core.py:242-252): department and activity from
    the compelling rule, geography inherited from the parent, protection flags
    from the rule's department, criticality zero.

    Their durations come from the rule, and are dropped for the same reason the
    parents' are.
    """
    rules = companion_catalogue(pairing_rules)
    parent = jobs.set_index("job_id")

    built = []
    for job_id in companions["job_id"].unique():
        parent_id, _, index = str(job_id).rpartition("c")
        k = int(index)
        parent_row = parent.loc[parent_id]
        rule = rules[parent_row["activity"]][k]
        dept = rule["compelled_dept"]
        activity = rule["companion_activity"]
        built.append({
            "job_id": job_id,
            "parent_job_id": parent_id,
            "dept": dept,
            "activity": activity,
            "section_id": parent_row["section_id"],
            "km_from": parent_row["km_from"],
            "km_to": parent_row["km_to"],
            # core.py:246-248 -- not read from a table, derived from the rule
            "needs_T": 1,
            "needs_P": int(dept == "TRD" and activity != "TRACTION_BOND_JUMPER"),
            "needs_D": int(dept == "SNT"),
            "needs_train_movements": 0,
            "needs_live_ohe": 0,
            "due_day": parent_row["due_day"],
            "criticality": 0.0,
            # Deliberately absent, because core.py does not set them.
            # core.Job defaults resources to () (core.py:118), and has no
            # min_block_min or priority field at all. Inheriting the parent's
            # would invent attributes the optimiser never sees -- and the
            # parent's resource class in particular would be a fabrication:
            # a companion consumes no fleet resource in this model.
            "resources": pd.NA,
            "min_block_min": pd.NA,
            "priority": pd.NA,
            # The rule itself is legitimate provenance, and for the four
            # companion activities absent from activities.csv it is the only
            # activity-level information there is.
            "compelled_by_rule_source": rule["source"],
            "compelled_by_rule_confidence": rule["confidence"],
        })
    return pd.DataFrame(built)


# -- assembly ---------------------------------------------------------------

@dataclass(frozen=True)
class TrainingTable:
    frame: pd.DataFrame
    feature_columns: tuple[str, ...]
    profile: str = ALL_FEATURES

    @property
    def rows(self) -> int:
        return len(self.frame)

    def features(self) -> pd.DataFrame:
        return self.frame[list(self.feature_columns)]

    def labels(self) -> pd.Series:
        return self.frame[LABEL]


def build(profile: str = ALL_FEATURES) -> TrainingTable:
    """Join execution history to everything legitimately known beforehand.

    `profile` selects the feature set: ALL_FEATURES keeps every legal column,
    GENERALISING additionally drops the near-identifiers. See NEAR_IDENTIFIERS.
    """
    execution = _read("execution.csv")
    companions_exec = _read("execution_companions.csv")
    jobs = _read("jobs.csv")
    activities = _read("activities.csv")
    sections = _read("sections.csv")
    resources = _read("resources.csv")
    requests = _read("block_requests.csv")
    pairing_rules = pd.read_csv(paths.PAIRING_RULES_CSV)

    base = jobs.copy()
    base["parent_job_id"] = pd.NA
    comp = companion_rows(companions_exec, jobs, pairing_rules)

    # One catalogue of every job the planner ever sees, base and companion.
    catalogue = pd.concat([base, comp], ignore_index=True)
    catalogue["is_companion"] = catalogue["parent_job_id"].notna().astype(int)
    catalogue["resource_class"] = catalogue["resources"].astype(str).str.rsplit(
        "_", n=1).str[0]
    catalogue.loc[catalogue["resources"].isna(), "resource_class"] = pd.NA
    catalogue["km_span"] = catalogue["km_to"] - catalogue["km_from"]

    observed = pd.concat([
        execution.assign(parent_job_id=pd.NA),
        companions_exec[["realisation", "job_id", LABEL, "parent_job_id"]],
    ], ignore_index=True)[["realisation", "job_id", LABEL]]

    frame = observed.merge(catalogue, on="job_id", how="left", validate="many_to_one")

    frame = frame.merge(activities.add_prefix("activity_"),
                        left_on="activity", right_on="activity_activity_id",
                        how="left", validate="many_to_one")
    frame = frame.merge(sections.add_prefix("section_"),
                        left_on="section_id", right_on="section_section_id",
                        how="left", validate="many_to_one")
    frame = frame.merge(resources.add_prefix("resource_"),
                        left_on="resource_class", right_on="resource_resource_class",
                        how="left", validate="many_to_one")
    frame = frame.merge(requests.add_prefix("request_"),
                        left_on="job_id", right_on="request_job_id",
                        how="left", validate="many_to_one")

    unmatched = frame[frame["activity"].isna()]
    if len(unmatched):
        raise ValueError(
            f"{len(unmatched)} execution rows matched no job: "
            f"{sorted(unmatched['job_id'].unique())[:5]}")

    return TrainingTable(frame, feature_columns(frame, profile), profile)


def activities_without_a_catalogue_entry() -> tuple[str, ...]:
    """Companion activities that exist only as pairing-rule targets.

    Four of the six -- SNT_ASSOCIATION, POINT_MOTOR_RESET,
    TRACTION_BOND_JUMPER, CABLE_ROD_CLEARANCE -- are named by pairing_rules.csv
    and are not rows in activities.csv. Nothing is broken: they are compelled
    work, not independently scheduled work, so they have no periodicity, no
    asset class and no catalogue duration of their own.

    The consequence for this table is that their activity_* features are NaN,
    and it is a data property rather than a join failure -- which is why it is
    named here and asserted in the tests instead of being silently filled.
    """
    activities = set(_read("activities.csv")["activity_id"])
    rules = pd.read_csv(paths.PAIRING_RULES_CSV)
    return tuple(sorted(set(rules["companion_activity"]) - activities))


def feature_columns(frame: pd.DataFrame,
                    profile: str = ALL_FEATURES) -> tuple[str, ...]:
    """Every column that is neither the label, nor a key, nor forbidden.

    Forbidden columns are matched on the BARE name after any join prefix is
    stripped, so activity_duration_mean_min is caught as readily as
    duration_mean_min. Prefixing is a join convenience; it must not be a way
    past the guard.
    """
    if profile not in (ALL_FEATURES, GENERALISING, SERVING):
        raise ValueError(f"unknown feature profile {profile!r}")
    dropped = IDENTIFIERS | (
        NEAR_IDENTIFIERS if profile == GENERALISING else frozenset())

    chosen = []
    for column in frame.columns:
        if column == LABEL or column in KEYS:
            continue
        if _bare(column) in FORBIDDEN or column in dropped:
            continue
        if profile == SERVING and not _servable(column):
            continue
        chosen.append(column)
    assert_no_leakage(chosen)
    return tuple(chosen)


def _servable(column: str) -> bool:
    """Can this column be produced from a core.Job at plan time?

    Either it is one of the job's own attributes, or it came from a reference
    table joined on one of them. Everything else -- the request table, the
    columns that live only in jobs.csv -- is unavailable when the planner runs
    and must not be trained on.
    """
    return (column in SERVING_JOB_COLUMNS
            or column.startswith(("activity_", "section_", "resource_")))


def _bare(column: str) -> str:
    """Strip a join prefix: activity_/section_/resource_/request_."""
    for prefix in ("activity_", "section_", "resource_", "request_"):
        if column.startswith(prefix):
            return column[len(prefix):]
    return column


def assert_no_leakage(columns) -> None:
    """The guard. An assertion, not a comment, and it runs on every build."""
    offenders = sorted(c for c in columns if _bare(c) in FORBIDDEN)
    if offenders:
        raise LeakageError(
            "these columns are the label's own generating parameters, or a "
            f"deterministic function of them: {offenders}. They cannot be "
            "features -- they are what the model is being asked to estimate. "
            "See the module docstring for where each one comes from.")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Build the ML training table.")
    ap.add_argument("--out", help="write the table here as CSV")
    ap.add_argument("--profile", default=ALL_FEATURES,
                    choices=[ALL_FEATURES, GENERALISING, SERVING])
    args = ap.parse_args(argv)

    table = build(args.profile)
    print(f"rows                {table.rows}")
    print(f"profile             {table.profile}")
    print(f"features            {len(table.feature_columns)}")
    print(f"label               {LABEL}  "
          f"[{table.labels().min():.1f}, {table.labels().max():.1f}]")
    print(f"jobs                {table.frame['job_id'].nunique()} "
          f"{table.frame.groupby('is_companion')['job_id'].nunique().to_dict()}")
    print(f"realisations        {table.frame['realisation'].nunique()}")
    print(f"excluded as leakage {sorted(FORBIDDEN)}")
    print(f"excluded as identity {sorted(IDENTIFIERS)}")
    if args.profile == GENERALISING:
        print(f"excluded as near-id  {sorted(NEAR_IDENTIFIERS)}")
    if args.out:
        table.frame.to_csv(args.out, index=False)
        print(f"written             {args.out}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
